import { useMemo, useState } from 'react';
import { AlertTriangle, Gauge, Pencil, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { AppShell } from '@/components/AppShell';
import { BudgetDialog } from '@/components/BudgetDialog';
import { currentMonth, money, useFinance, type Budget } from '@/lib/finance';
export default function Budgets(){
 const {state,saveBudget,deleteBudget}=useFinance();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Budget>();const [deleting,setDeleting]=useState<Budget>();const tx=state.transactions.filter(t=>t.type==='Expense'&&t.date.slice(0,7)===currentMonth());
 const spend=(b:Budget)=>tx.filter(t=>b.scope==='global'||t.category===b.category).reduce((a,t)=>a+t.amount,0);
 const sorted=useMemo(()=>state.budgets,[state.budgets]);
 return <AppShell><div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Gentle guardrails</p><h1 className="mt-2 font-serif text-4xl font-bold">Budgets</h1><p className="mt-2 max-w-lg text-sm text-muted-foreground">Give your monthly spending a shape that feels supportive, not restrictive.</p></div><Button onClick={()=>{setEditing(undefined);setOpen(true)}} data-testid="button-add-budget"><Plus size={17}/> Add budget</Button></div>
 <div className="grid gap-4 sm:grid-cols-3"><SummaryCard label="Tracked budgets" value={String(state.budgets.length)} icon={<Gauge size={18}/>}/><SummaryCard label="Monthly limit" value={money(state.budgets.reduce((a,b)=>a+b.monthlyLimit,0),state.settings.currency)} icon={<ShieldCheck size={18}/>}/><SummaryCard label="Month to date" value={money(tx.reduce((a,t)=>a+t.amount,0),state.settings.currency)} icon={<Gauge size={18}/>}/></div>
 {sorted.length?<div className="grid gap-5 md:grid-cols-2">{sorted.map(b=>{const value=spend(b),pct=b.monthlyLimit?value/b.monthlyLimit*100:0;return <Card key={b.id} data-testid={`card-budget-${b.id}`}><CardHeader className="flex flex-row items-start justify-between pb-3"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-muted-foreground">{b.scope==='global'?'All expenses':'Category budget'}</p><CardTitle className="mt-2 font-serif text-xl">{b.scope==='global'?'Monthly spending':b.category}</CardTitle></div><div className="flex"><Button variant="ghost" size="icon" onClick={()=>{setEditing(b);setOpen(true)}} data-testid={`button-edit-budget-${b.id}`}><Pencil size={15}/></Button><Button variant="ghost" size="icon" onClick={()=>setDeleting(b)} data-testid={`button-delete-budget-${b.id}`}><Trash2 size={15}/></Button></div></CardHeader><CardContent><div className="mb-3 flex items-end justify-between"><div><span data-testid={`text-budget-spend-${b.id}`} className="font-serif text-2xl font-bold">{money(value,state.settings.currency)}</span><span className="ml-2 text-xs text-muted-foreground">of {money(b.monthlyLimit,state.settings.currency)}</span></div><span className={`text-xs font-bold ${pct>100?'text-red-600':pct>80?'text-amber-700':'text-primary'}`}>{Math.round(pct)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div data-testid={`progress-budget-${b.id}`} className={`h-full rounded-full transition-all ${pct>100?'bg-red-500':pct>80?'bg-amber-500':'bg-primary'}`} style={{width:`${Math.min(pct,100)}%`}}/></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground">{pct>100?<><AlertTriangle size={14} className="text-red-600"/>Over by {money(value-b.monthlyLimit,state.settings.currency)}</>:pct>80?<><AlertTriangle size={14} className="text-amber-600"/>Getting close to your limit</>:<><ShieldCheck size={14} className="text-primary"/>Room to breathe</>}</div></CardContent></Card>})}</div>:<Card><CardContent className="py-20 text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-accent"><ShieldCheck className="text-primary"/></div><p className="font-serif text-xl font-bold">No budgets yet</p><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">A budget is a friendly reference point for your month, not a test you can fail.</p><Button onClick={()=>setOpen(true)} className="mt-5" data-testid="button-empty-add-budget"><Plus size={16}/> Set your first budget</Button></CardContent></Card>}
 <BudgetDialog open={open} onOpenChange={setOpen} editing={editing} onSave={saveBudget}/>
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this budget?</AlertDialogTitle><AlertDialogDescription>Your transaction history will stay safe. Only this monthly guardrail will be removed.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-budget-delete">Keep it</AlertDialogCancel><AlertDialogAction onClick={()=>{if(deleting)deleteBudget(deleting.id);setDeleting(undefined)}} data-testid="button-confirm-budget-delete">Remove budget</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div></AppShell>
}
function SummaryCard({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <Card><CardContent className="flex items-center gap-3 p-5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-accent text-primary">{icon}</div><div><p className="text-xs text-muted-foreground">{label}</p><p data-testid={`summary-${label.toLowerCase().replaceAll(' ','-')}`} className="mt-1 font-serif text-xl font-bold">{value}</p></div></CardContent></Card>}