import { Link } from 'wouter';
import { ArrowDownLeft, ArrowUpRight, ChevronRight, Plus, PiggyBank, TrendingUp, Wallet } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, PieChart, Pie, Cell } from 'recharts';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AppShell } from '@/components/AppShell';
import { TransactionDialog } from '@/components/TransactionDialog';
import { TransactionRow } from '@/components/TransactionRow';
import { currentMonth, monthKey, money, useFinance } from '@/lib/finance';
import { useMemo, useState } from 'react';

const COLORS=['#275b4a','#e3b85e','#d77c61','#70a5aa','#987eb1','#9a8266','#7aa36f','#cc8e54'];
export default function Dashboard() {
  const {state,saveTransaction}=useFinance(); const [dialog,setDialog]=useState(false);
  const currency=state.settings.currency, month=currentMonth();
  const monthTx=state.transactions.filter(t=>monthKey(t.date)===month), income=monthTx.filter(t=>t.type==='Income').reduce((a,t)=>a+t.amount,0), expenses=monthTx.filter(t=>t.type==='Expense').reduce((a,t)=>a+t.amount,0), net=income-expenses;
  const rate=income?Math.round(net/income*100):0;
  const categories=useMemo(()=>Object.entries(monthTx.filter(t=>t.type==='Expense').reduce<Record<string,number>>((a,t)=>(a[t.category]=(a[t.category]||0)+t.amount,a),{})).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value),[monthTx]);
  const chart=useMemo(()=>{const months=[...Array(5)].map((_,i)=>{const d=new Date();d.setMonth(d.getMonth()-4+i);return d.toISOString().slice(0,7)});return months.map(key=>{const tx=state.transactions.filter(t=>monthKey(t.date)===key);return {month:new Date(`${key}-15T12:00:00`).toLocaleDateString(undefined,{month:'short'}),Income:tx.filter(t=>t.type==='Income').reduce((a,t)=>a+t.amount,0),Expenses:tx.filter(t=>t.type==='Expense').reduce((a,t)=>a+t.amount,0)}})},[state.transactions]);
  const latest=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  return <AppShell><div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Your money at a glance</p><h1 className="mt-2 font-serif text-4xl font-bold tracking-tight md:text-5xl">Good morning, <span className="text-primary">let's check in.</span></h1><p className="mt-3 max-w-xl text-sm text-muted-foreground">A calm snapshot of what came in, what went out, and what is still yours to direct this month.</p></div><Button onClick={()=>setDialog(true)} data-testid="button-add-transaction-dashboard"><Plus size={17}/> Add transaction</Button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <Metric title="Money in" value={money(income,currency)} meta="This month" icon={<ArrowDownLeft size={18}/>} tone="green"/>
      <Metric title="Money out" value={money(expenses,currency)} meta="This month" icon={<ArrowUpRight size={18}/>} tone="orange"/>
      <Metric title="Net position" value={money(net,currency)} meta={net>=0?'A positive month so far':'More out than in'} icon={<Wallet size={18}/>} tone="gold"/>
      <Metric title="Savings rate" value={`${rate}%`} meta={income?'Of monthly income':'Add income to calculate'} icon={<PiggyBank size={18}/>} tone="blue"/>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.45fr_0.8fr]">
      <Card className="overflow-hidden"><CardHeader className="flex flex-row items-start justify-between pb-0"><div><p className="eyebrow">Five month rhythm</p><CardTitle className="mt-1 font-serif text-2xl">Income vs. expenses</CardTitle></div><TrendingUp className="text-primary" size={20}/></CardHeader><CardContent><div className="h-[260px] pt-6" data-testid="chart-income-expenses"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#275b4a" stopOpacity=".22"/><stop offset="100%" stopColor="#275b4a" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7e3d9"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:12,fill:'#8c918b'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#8c918b'}} tickFormatter={v=>`$${v>=1000?`${(v/1000).toFixed(1)}k`:v}`}/><Tooltip formatter={(v:number)=>money(v,currency)} contentStyle={{borderRadius:12,border:'1px solid #e7e3d9',background:'#fffdf8'}}/><Area type="monotone" dataKey="Income" stroke="#275b4a" fill="url(#incomeFill)" strokeWidth={2.5}/><Area type="monotone" dataKey="Expenses" stroke="#d77c61" fill="none" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-primary"/>Income</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#d77c61]"/>Expenses</span></div></CardContent></Card>
      <Card><CardHeader><p className="eyebrow">This month</p><CardTitle className="mt-1 font-serif text-2xl">Where it goes</CardTitle></CardHeader><CardContent>{categories.length?<><div className="mx-auto h-[185px] w-full" data-testid="chart-expense-categories"><ResponsiveContainer><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={56} outerRadius={80} paddingAngle={3}>{categories.map((x,i)=><Cell key={x.name} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip formatter={(v:number)=>money(v,currency)}/></PieChart></ResponsiveContainer></div><div className="space-y-2">{categories.slice(0,4).map((x,i)=><div key={x.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full" style={{backgroundColor:COLORS[i%COLORS.length]}}/>{x.name}</span><strong>{money(x.value,currency)}</strong></div>)}</div></>:<div className="flex h-[240px] flex-col items-center justify-center text-center"><div className="mb-3 grid h-12 w-12 place-items-center rounded-2xl bg-accent"><PiggyBank className="text-primary"/></div><p className="font-semibold">No spending here yet</p><p className="mt-1 text-xs text-muted-foreground">Your first expense will bring this view to life.</p></div>}</CardContent></Card>
    </div>
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><p className="eyebrow">Latest activity</p><CardTitle className="mt-1 font-serif text-2xl">Recent transactions</CardTitle></div><Link href="/transactions" data-testid="link-view-all-transactions" className="flex items-center gap-1 text-sm font-bold text-primary">View all <ChevronRight size={15}/></Link></CardHeader><CardContent>{latest.length?<div>{latest.map(t=><TransactionRow key={t.id} transaction={t} currency={currency}/>)}</div>:<EmptyTransactions/>}</CardContent></Card>
    <TransactionDialog open={dialog} onOpenChange={setDialog} onSave={tx=>{saveTransaction(tx);setDialog(false)}}/>
  </div></AppShell>;
}
function Metric({title,value,meta,icon,tone}:{title:string;value:string;meta:string;icon:React.ReactNode;tone:string}) { return <Card className="relative overflow-hidden"><CardContent className="p-5"><div className={`mb-7 grid h-9 w-9 place-items-center rounded-xl ${tone==='green'?'bg-emerald-100 text-emerald-700':tone==='orange'?'bg-orange-100 text-orange-700':tone==='gold'?'bg-amber-100 text-amber-700':'bg-sky-100 text-sky-700'}`}>{icon}</div><p className="text-sm text-muted-foreground">{title}</p><p data-testid={`metric-${title.toLowerCase().replaceAll(' ','-')}`} className="mt-1 font-serif text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{meta}</p></CardContent></Card> }
function EmptyTransactions(){return <div className="rounded-2xl border border-dashed border-border bg-muted/40 px-5 py-10 text-center"><p className="font-semibold">Your story starts here</p><p className="mt-1 text-sm text-muted-foreground">Add a transaction to see your recent activity.</p><Link href="/transactions" data-testid="link-empty-add-transaction" className="mt-4 inline-flex text-sm font-bold text-primary">Add your first transaction <ChevronRight size={15}/></Link></div>}