import { useRef, useState } from 'react';
import { Check, Download, FileText, RotateCcw, Settings2, Trash2, Upload } from 'lucide-react';
import { AppShell } from '@/components/AppShell';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { useFinance, type Currency } from '@/lib/finance';
export default function SettingsPage(){
 const {state,setCurrency,restoreSamples,reset}=useFinance();const [confirm,setConfirm]=useState<'restore'|'reset'>();const [saved,setSaved]=useState(false);const currencyOptions:[Currency,string][]=[['USD','US Dollar ($)'],['EUR','Euro (€)'],['GBP','British Pound (£)'],['INR','Indian Rupee (₹)']]; const fileRef=useRef<HTMLAnchorElement>(null);
 const exportCsv=()=>{const rows=[['Date','Type','Amount','Category','Payment method','Notes'],...state.transactions.map(t=>[t.date,t.type,String(t.amount),t.category,t.paymentMethod,t.notes])];const csv=rows.map(row=>row.map(x=>`"${x.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));if(fileRef.current){fileRef.current.href=url;fileRef.current.click()}setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <AppShell><div className="max-w-3xl space-y-7"><div><p className="eyebrow">Your preferences</p><h1 className="mt-2 font-serif text-4xl font-bold">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Pocketwise keeps everything in this browser, ready when you are.</p></div>
 <Card><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-2xl"><Settings2 size={20} className="text-primary"/> Display & currency</CardTitle></CardHeader><CardContent><label className="text-sm font-semibold" htmlFor="currency">Display currency</label><p className="mt-1 text-xs text-muted-foreground">Used for every total, chart and budget across your workspace.</p><select id="currency" value={state.settings.currency} onChange={e=>{setCurrency(e.target.value as Currency);setSaved(true);setTimeout(()=>setSaved(false),1800)}} data-testid="select-currency" className="field-input mt-3 max-w-sm">{currencyOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>{saved&&<span data-testid="status-currency-saved" className="ml-3 inline-flex items-center gap-1 text-xs font-bold text-primary"><Check size={14}/> Saved</span>}</CardContent></Card>
 <Card><CardHeader><CardTitle className="font-serif text-2xl">Your data</CardTitle></CardHeader><CardContent className="divide-y divide-border/60 p-0"><SettingRow icon={<Download size={18}/>} title="Export transactions" text={`Download ${state.transactions.length} transactions as a clean CSV file.`}><Button variant="outline" onClick={exportCsv} data-testid="button-export-csv"><Download size={15}/> Export CSV</Button><a ref={fileRef} className="hidden" download="pocketwise-transactions.csv" data-testid="link-csv-download">Download</a></SettingRow><SettingRow icon={<Upload size={18}/>} title="Restore sample data" text="Bring back a thoughtful set of transactions and budgets to explore."><Button variant="outline" onClick={()=>setConfirm('restore')} data-testid="button-restore-samples"><RotateCcw size={15}/> Restore samples</Button></SettingRow><SettingRow icon={<Trash2 size={18}/>} title="Wipe local data" text="Remove every transaction and budget from this browser."><Button variant="outline" className="text-destructive hover:text-destructive" onClick={()=>setConfirm('reset')} data-testid="button-reset-data"><Trash2 size={15}/> Reset workspace</Button></SettingRow></CardContent></Card>
 <div className="rounded-2xl border border-border/60 bg-accent/50 p-5"><div className="flex gap-3"><FileText size={18} className="mt-0.5 text-primary"/><div><p className="text-sm font-bold">A note about privacy</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Your data never leaves this browser. Clearing site data or using reset will remove it permanently; there is no account recovery.</p></div></div></div>
 <AlertDialog open={!!confirm} onOpenChange={v=>!v&&setConfirm(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm==='reset'?'Reset your workspace?':'Restore sample data?'}</AlertDialogTitle><AlertDialogDescription>{confirm==='reset'?'This clears all transactions and budgets and cannot be undone.':'This replaces your current local data with the Pocketwise sample workspace.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-data-action">Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{confirm==='reset'?reset():restoreSamples();setConfirm(undefined)}} data-testid={`button-confirm-${confirm}-action`}>{confirm==='reset'?'Reset workspace':'Restore samples'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div></AppShell>
}
function SettingRow({icon,title,text,children}:{icon:React.ReactNode;title:string;text:string;children:React.ReactNode}){return <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-accent text-primary">{icon}</div><div className="flex-1"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{text}</p></div>{children}</div>}