import { useMemo, useState } from 'react';
import { CalendarDays, Filter, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { AppShell } from '@/components/AppShell';
import { TransactionDialog } from '@/components/TransactionDialog';
import { TransactionRow } from '@/components/TransactionRow';
import { CATEGORIES, formatDate, monthKey, useFinance, type Transaction } from '@/lib/finance';
export default function Transactions(){
 const {state,saveTransaction,deleteTransaction}=useFinance(); const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Transaction>();const [deleting,setDeleting]=useState<Transaction>(); const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [type,setType]=useState('all');const [range,setRange]=useState('this');
 const now=new Date(), current=monthKey(now.toISOString()); const filtered=useMemo(()=>[...state.transactions].filter(t=>(!query||t.notes.toLowerCase().includes(query.toLowerCase())||t.category.toLowerCase().includes(query.toLowerCase()))&&(category==='all'||t.category===category)&&(type==='all'||t.type===type)&&(range==='all'||range==='this'&&monthKey(t.date)===current||range==='last'&&monthKey(t.date)===monthKey(new Date(now.getFullYear(),now.getMonth()-1,1).toISOString()))).sort((a,b)=>b.date.localeCompare(a.date)),[state.transactions,query,category,type,range,current]);
 const grouped=filtered.reduce<Record<string,Transaction[]>>((a,t)=>(a[t.date]??=[],a[t.date].push(t),a),{});
 const clear=()=>{setQuery('');setCategory('all');setType('all');setRange('this')};
 return <AppShell><div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">The full picture</p><h1 className="mt-2 font-serif text-4xl font-bold">Transactions</h1><p className="mt-2 text-sm text-muted-foreground">A simple record of every inflow and outflow.</p></div><Button onClick={()=>{setEditing(undefined);setOpen(true)}} data-testid="button-add-transaction"><Plus size={17}/> Add transaction</Button></div>
 <Card><CardContent className="p-4"><div className="flex flex-col gap-3 xl:flex-row"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} data-testid="input-search-transactions" placeholder="Search notes or categories" className="field-input pl-10"/></div><div className="flex flex-wrap gap-2"><select value={range} onChange={e=>setRange(e.target.value)} data-testid="select-date-range" className="field-input w-auto"><option value="this">This month</option><option value="last">Last month</option><option value="all">All time</option></select><select value={type} onChange={e=>setType(e.target.value)} data-testid="select-type-filter" className="field-input w-auto"><option value="all">All types</option><option>Expense</option><option>Income</option></select><select value={category} onChange={e=>setCategory(e.target.value)} data-testid="select-category-filter" className="field-input w-auto"><option value="all">All categories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select>{(query||category!=='all'||type!=='all'||range!=='this')&&<Button variant="ghost" onClick={clear} data-testid="button-clear-filters"><X size={15}/> Clear</Button>}</div></div><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal size={14}/>{filtered.length} matching {filtered.length===1?'transaction':'transactions'}</div></CardContent></Card>
 <Card><CardContent className="p-5 md:p-7">{Object.keys(grouped).length?Object.entries(grouped).map(([date,txs])=><section key={date} className="mb-7 last:mb-0"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-muted-foreground"><CalendarDays size={14}/>{formatDate(date)}</div>{txs.map(t=><TransactionRow key={t.id} transaction={t} currency={state.settings.currency} onEdit={()=>{setEditing(t);setOpen(true)}} onDelete={()=>setDeleting(t)}/>)}</section>):<div className="py-16 text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-accent"><Filter className="text-primary"/></div><p className="font-serif text-xl font-bold">{state.transactions.length?'Nothing matches those filters':'No transactions yet'}</p><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">{state.transactions.length?'Try widening your search or clearing a filter.':'Start with one expense or income entry. It only takes a moment.'}</p>{state.transactions.length?<Button variant="outline" onClick={clear} className="mt-5" data-testid="button-empty-clear-filters">Clear filters</Button>:<Button onClick={()=>setOpen(true)} className="mt-5" data-testid="button-empty-add-transaction"><Plus size={16}/> Add transaction</Button>}</div>}</CardContent></Card>
 <TransactionDialog open={open} onOpenChange={setOpen} editing={editing} onSave={tx=>{saveTransaction(tx);setOpen(false)}}/>
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this transaction?</AlertDialogTitle><AlertDialogDescription>This will remove {deleting?.notes||deleting?.category} from your local record. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="button-cancel-delete">Keep it</AlertDialogCancel><AlertDialogAction onClick={()=>{if(deleting)deleteTransaction(deleting.id);setDeleting(undefined)}} data-testid="button-confirm-delete">Delete transaction</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div></AppShell>
}